Show On First Join: true
Show On Every Join: false

Title: Rules
Author: Server
Rules:
  - "1. No Cheating/Hacking"
  - "2. No Spamming"
  - "3. No Harassment or Threats"
  - "NEXT PAGE"
  - "4. No Racism"
  - "5. No Sexual Conduct"
  - "6. Use Common Sense"